### ISSUE TITLE
Make Installation easier for user

### ISSUE THREAD

**Issue by IsaBeau-Dev** [CK-3-Mod-Template/CK-3-Mod-Template#14]
**Subtasks**
- [x] Create README
- [x] Leave to option in to manually run the application
- [x] Add option to create .exe (and other executables) manually
- [x] Add option to create .exe (and other executables) via CL
- [x] Add option to create .exe (and other executables) automatically via Github Workflow
