### ISSUE TITLE
Create list of edited vanilla files

### ISSUE THREAD

**Issue by IsaBeau-Dev** [CK-3-Mod-Template/CK-3-Mod-Template#23]
**Short description**
This will be based on the list created in #4 
**Details**
Comes from https://discord.com/channels/735413460439007241/1313969242177011855/1314213939055296563
**Subtasks**
- [ ] Compare files inside mod folder with list of vanilla files
- [ ] find a way to display in in GUI ?
- [ ] Dump the matches found into a file ?
