### ISSUE TITLE
Something like a main menu ?

### ISSUE THREAD

**Issue by IsaBeau-Dev** [CK-3-Mod-Template/CK-3-Mod-Template#31]
**Short description**
Should make navigation easier and fix some issue with the current setup.
**Details**
This looks ok but some func is mixed. For example open mod folder button should only be visable when the mod was already created.
**Subtasks**
- [x] Create main menu
- [ ] What Pages/Windows should exist ?
  - My ideas: 
  - [ ] Help page with some basic comments and then links to wiki or discord server
  - [x] Create Mod
  - [ ] Update Mod
  - [ ] Get List of edited vanilla files
  - [ ] ...
- [x] Settings
  - [x] make settings persistent and add dark/light mode
- [x] Show current version in main menu with colors
- [x] show current version on initial setup too
- [x] use log level set in settings in the backend
