### ISSUE TITLE
Setup GUI

### ISSUE THREAD

**Issue by IsaBeau-Dev** [CK-3-Mod-Template/CK-3-Mod-Template#5]
**Short description**
This should make the start into modding as easy as possible
**Details**
Setup the mod dir so the user can just clone them soemwhere and after setting stuff inside gui the mod will be created
**Subtasks**
- [x] Create GUI
- [x] Enter (short) Mod Name and tags in the gui (#2 )
- [x] Get ck 3 supported version for the .mod file
- [x] Create .mod files and folder inside documents
  - [x] Create the .mod file inside documents
  - [x] Create folder with mod name in it
  - [x] Create descriptor.mod inside the created folder
  - [x] #6
- [x] Implement Folder Structure with Placeholder
 - [x] Essentials folder that containts all folders and files that will always will be copied over
 - [x] Optional folder ...
- [x] Implement Debug Var so the copy either gets created in the clone or in documents
- [x] #1 

**Dependencies**
This task depends on #6  to be finished
